-- example: INSERT INTO table (column1, column2) VALUES (value1, value2);
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 1');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 2');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 3');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เกาะกลาง');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 4');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 5');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 6');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 7');
INSERT INTO public.ref_asset_lane ("name") VALUES ( 'เลน 8');