-- example: INSERT INTO table (column1, column2) VALUES (value1, value2);
INSERT INTO public.ref_asset_table VALUES (3, 1, 'road_asset_in_speed', 'ป้าย MS', 'public://icons/icon32/orangelight.png', NULL, 3, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (6, 7, 'road_asset_in_trafficpole', 'เสาหลักจราจร (เสาล้มลุก)', 'public://icons/icon32/trafficpole.png', NULL, 6, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (30, 6, 'road_asset_in_flashlight', 'ไฟกระพริบเตือน', 'public://icons/icon32/orangelight.png', NULL, 30, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (15, 3, 'road_asset_in_arrow', 'เส้นลูกศร', 'public://icons/icon32/arrow.png', NULL, 15, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (16, 3, 'road_asset_in_stripline', 'เส้นก้างปลา', 'public://icons/icon32/stripline.png', NULL, 16, true, false, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (44, 6, 'road_asset_out_platelight', 'ไฟส่องหน้าป้าย', 'public://icons/icon32/platelight.png', NULL, 44, false, true, 3, FALSE);
INSERT INTO public.ref_asset_table VALUES (9, 7, 'road_asset_in_barrier', 'ม่านบังแสงและประกับกันล้ม', 'public://icons/icon32/barrier.png', NULL, 9, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (5, 7, 'road_asset_in_km', 'หลักกิโลเมตร', 'public://icons/icon32/milestone.png', NULL, 5, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (8, 7, 'road_asset_in_reflect', 'เป้าสะท้อนแสง', 'public://icons/icon32/reflec.png', NULL, 8, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (21, 7, 'road_asset_in_toilet', 'ห้องน้ำสาธารณะ', 'public://icons/icon32/toilet.png', NULL, 21, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (23, 7, 'road_asset_in_weight', 'ด่านชั่งน้ำหนัก', 'public://icons/icon32/weight.png', NULL, 23, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (22, 7, 'road_asset_in_emerrest', 'จุดพักรถฉุกเฉิน', 'public://icons/icon32/emerrest.png', NULL, 22, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (24, 8, 'road_asset_in_tollplaza', 'ด่านเก็บเงินค่าธรรมเนียมผ่านทาง', 'public://icons/icon32/tollplaza.png', NULL, 24, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (12, 7, 'road_asset_in_fence', 'รั้วเขตทาง', NULL, '#00FF00', 12, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (13, 7, 'road_asset_in_noisebarrier', 'กำแพงกันเสียง', NULL, '#00FFFF', 13, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (14, 3, 'road_asset_in_line', 'เส้นจราจร', NULL, '#FF00FF', 14, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (18, 4, 'road_asset_in_roadstud', 'Road Stud', 'public://icons/icon32/roadstud.png', NULL, 18, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (17, 4, 'road_asset_in_antiskid', 'Red Anti-Skid', NULL, '#0FFF00', 17, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (20, 7, 'road_asset_in_manholecover', 'ฝาท่อระบายน้ำ', 'public://icons/icon32/manholecover.png', NULL, 20, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (7, 7, 'road_asset_in_crashcushion', 'ถังกันชนหัวเกาะและอุปกรณ์ดูดซับแรงกระแทก', 'public://icons/icon32/crashcushion.png', NULL, 7, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (25, 8, 'road_asset_in_kiosk', 'ตู้เก็บเงิน', 'public://icons/icon32/orangelight.png', NULL, 25, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (26, 8, 'road_asset_in_division', 'ป้าย Division', 'public://icons/icon32/division.png', NULL, 26, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (27, 7, 'road_asset_in_building', 'อาคาร', 'public://icons/icon32/building.png', NULL, 27, true, true, 3, FALSE);
INSERT INTO public.ref_asset_table VALUES (28, 5, 'road_asset_in_fingerjoint', 'Finger Joint', 'public://icons/icon32/fingerjoint.png', NULL, 28, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (29, 5, 'road_asset_in_plugjoint', 'Plug Joint', 'public://icons/icon32/plugjoint.png', NULL, 29, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (42, 7, 'road_asset_in_notes', 'อุปกรณ์ตรวจสอบจราจร', 'public://icons/icon32/20210319_180834_security-camera.png', NULL, 42, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (40, 7, 'road_asset_in_cctv', 'CCTV', 'public://icons/icon32/cctv.png', NULL, 40, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (48, 5, 'road_asset_in_expansionjoint', 'Strip Seal Joint', 'public://icons/icon32/expansionjoint.png', NULL, 48, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (54, 5, 'road_asset_in_longitudinaljoint', 'Longitudinal Joint', NULL, '#FF0000', 54, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (32, 6, 'road_asset_in_platelight', 'ไฟส่องหน้าป้าย', 'public://icons/icon32/platelight.png', NULL, 32, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (31, 6, 'road_asset_in_electricpost', 'ไฟส่องสว่าง', 'public://icons/icon32/electricpost.png', NULL, 31, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (35, 6, 'road_asset_in_transformer', 'หม้อแปลงไฟฟ้า', 'public://icons/icon32/transformer.png', NULL, 35, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (33, 6, 'road_asset_in_drawpit', 'Draw Pit', 'public://icons/icon32/drawpit.png', NULL, 33, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (36, 6, 'road_asset_in_pole', 'เสาไฟ', 'public://icons/icon32/pole.png', NULL, 36, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (37, 7, 'road_asset_in_safetyswitch', 'Safety Switch', 'public://icons/icon32/safetyswitch.png', NULL, 37, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (38, 7, 'road_asset_in_supplypillar', 'Supply Pillar', 'public://icons/icon32/supplypillar.png', NULL, 38, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (46, 7, 'road_asset_in_phone', 'ETS', 'public://icons/icon32/phone.png', NULL, 39, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (41, 7, 'road_asset_in_refpin', 'หมุดอ้างอิง', 'public://icons/icon32/refpin.png', NULL, 41, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (34, 6, 'road_asset_in_cable', 'สายไฟ', '', '#F0F0FF', 34, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (4, 1, 'road_asset_in_ms', 'ป้าย MS', 'public://icons/icon32/ms.png', NULL, 4, true, false, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (43, 1, 'road_asset_out_sign', 'ป้ายจราจร', 'public://icons/icon32/sign.png', NULL, 43, false, true, 3, FALSE);
INSERT INTO public.ref_asset_table VALUES (47, 7, 'road_asset_in_trafficlight', 'สัญญาณไฟจราจร', 'public://icons/icon32/trafficlight.png', NULL, 47, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (52, 7, 'road_asset_building', 'ทดสอบสินทรัพย์อาคาร', NULL, NULL, 52, true, false, 3, FALSE);
INSERT INTO public.ref_asset_table VALUES (53, 13, 'road_asset_in_note', 'บันทึก', 'public://icons/icon32/20210304_150916_บันทึก.png', NULL, 53, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (45, 7, 'road_asset_in_curve', 'หลักนำโค้ง', 'public://icons/icon32/orangelight.png', NULL, 45, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (2, 1, 'road_asset_in_vms', 'ป้าย VMS', 'public://icons/icon32/VMS.png', NULL, 2, true, true, 1, FALSE);
INSERT INTO public.ref_asset_table VALUES (51, 3, 'road_asset_in_herringboneline', 'เส้นก้างปลา', '', '#7DB700', 51, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (11, 7, 'road_asset_in_emermedian', 'ทางกลับรถฉุกเฉินบนทางพิเศษ', NULL, '#FFFF00', 11, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (10, 7, 'road_asset_in_guardrail', 'ราวกันอันตราย', NULL, '#FF0000', 10, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (19, 4, 'road_asset_in_speedbar', 'Optical Speed Bar', NULL, '#FF00FF', 19, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (55, 7, 'road_asset_in_wall', 'กำแพงกันตก', NULL, '#FF0000', 55, true, true, 2, FALSE);
INSERT INTO public.ref_asset_table VALUES (1, 1, 'road_asset_in_sign', 'ป้ายจราจร', 'public://icons/icon32/sign.png', NULL, 1, true, true, 1, FALSE);
SELECT setval('ref_asset_table_id_seq', 55, true);