-- example: INSERT INTO table (column1, column2) VALUES (value1, value2);
INSERT INTO public.params_condition VALUES (7, 1, 6, 0, '<=', 1.5, '<', 'MPD');
INSERT INTO public.params_condition VALUES (13, 1, 7, 15, '<=', 20, '<', 'RUT');
INSERT INTO public.params_condition VALUES (15, 1, 8, 20, '<=', 99, '<', 'RUT');
INSERT INTO public.params_condition VALUES (18, 1, 7, 0.25, '<=', 0.32, '<', 'IFI');
INSERT INTO public.params_condition VALUES (2, 1, 2, 2.5, '<=', 3.5, '<', 'IRI');
INSERT INTO public.params_condition VALUES (3, 1, 3, 3.5, '<=', 5, '<', 'IRI');
INSERT INTO public.params_condition VALUES (4, 1, 4, 5, '<=', 5.5, '<', 'IRI');
INSERT INTO public.params_condition VALUES (5, 1, 5, 5.5, '<=', 99, '<', 'IRI');
INSERT INTO public.params_condition VALUES (11, 1, 1, 0, '<=', 10, '<', 'RUT');
INSERT INTO public.params_condition VALUES (12, 1, 2, 10, '<=', 15, '<', 'RUT');
INSERT INTO public.params_condition VALUES (16, 1, 1, 0.4, '<=', 99, '<', 'IFI');
INSERT INTO public.params_condition VALUES (17, 1, 2, 0.32, '<=', 0.4, '<', 'IFI');
INSERT INTO public.params_condition VALUES (20, 1, 8, 0, '<=', 0.25, '<', 'IFI');
INSERT INTO public.params_condition VALUES (1, 1, 1, 0, '<=', 2.5, '<', 'IRI');
INSERT INTO public.params_condition VALUES (6, 1, 1, 1.5, '<=', 99, '<', 'MPD');
SELECT setval('params_condition_id_seq', 20, true);