FROM golang:1.21.1-alpine AS builder
WORKDIR /go/src/gitlab.com/mims-api-service




RUN apk update && apk add git
RUN apk add chromium
RUN go install github.com/swaggo/swag/cmd/swag@v1.8.12

COPY go.mod .
# Download and install any required dependencies
RUN go mod download 


# Copy the current directory contents into the container at /app
COPY . .

RUN swag init
RUN go mod tidy

COPY ./public ./public

#Copy env_stage file to .env
COPY ./env_stage .env

# Build the Go app
RUN go build -v -o main .


# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
