package models

import "time"

// Todo ...
type Hsms01Intersection struct {
	Id                              int       `gorm:"column:id"`
	intersectionId                  int       `gorm:"column:intersection_id"`
	SectionPartId                   int       `gorm:"column:section_part_id"`
	SectionGid                      int       `gorm:"column:section_gid"`
	SubsectionId                    int       `gorm:"column:subsection_id"`
	Depot                           int       `gorm:"column:depot"`
	Junction                        string    `gorm:"column:junction"`
	Km                              string    `gorm:"column:km"`
	IntersectTypeId                 int       `gorm:"column:intersect_type_id"`
	IntersectTypeText               string    `gorm:"column:intersect_type_text"`
	Feature                         int       `gorm:"column:feature"`
	TrafficControl                  int       `gorm:"column:traffic_control"`
	ResponsibleTrafficlight         int       `gorm:"column:responsible_trafficlight"`
	ResponsibleFlashlight           int       `gorm:"column:responsible_flashlight"`
	ResponsibleTrafficSign          int       `gorm:"column:responsible_traffic_sign"`
	HasLight                        int       `gorm:"column:has_light"`
	ResponsibleLight                int       `gorm:"column:responsible_light"`
	ResponsibleLightFl              int       `gorm:"column:responsible_light_fl"`
	ResponsibleLightHm              int       `gorm:"column:responsible_light_hm"`
	ResponsibleLightOther           int       `gorm:"column:responsible_light_other"`
	Surface                         int       `gorm:"column:surface"`
	Width                           float64   `gorm:"column:width"`
	Row                             string    `gorm:"column:row"`
	LaneCount                       int       `gorm:"column:lane_count"`
	Route2                          string    `gorm:"column:route2"`
	Control2                        string    `gorm:"column:control2"`
	Km2                             string    `gorm:"column:km2"`
	Surface2                        int       `gorm:"column:surface2"`
	Width2                          float64   `gorm:"column:width2"`
	Row2                            string    `gorm:"column:row2"`
	Agency2                         string    `gorm:"column:agency2"`
	Route3                          string    `gorm:"column:route3"`
	Control3                        string    `gorm:"column:control3"`
	Km3                             string    `gorm:"column:km3"`
	Surface3                        int       `gorm:"column:surface3"`
	Width3                          float64   `gorm:"column:width3"`
	Row3                            string    `gorm:"column:row3"`
	LaneCount3                      int       `gorm:"column:lane_count3"`
	Agency3                         string    `gorm:"column:agency3"`
	Route4                          string    `gorm:"column:route4"`
	Control4                        string    `gorm:"column:control4"`
	Km4                             string    `gorm:"column:km4"`
	Surface4                        int       `gorm:"column:surface4"`
	Width4                          float64   `gorm:"column:width4"`
	Row4                            string    `gorm:"column:row4"`
	LaneCount4                      int       `gorm:"column:lane_count4"`
	Agency4                         string    `gorm:"column:agency4"`
	Remark                          string    `gorm:"column:remark"`
	Status                          string    `gorm:"column:status"`
	ApproveStatus                   string    `gorm:"column:approve_status"`
	Revision                        int       `gorm:"column:revision"`
	UpdateBy                        string    `gorm:"column:update_by"`
	UpdateDate                      time.Time `gorm:"column:update_date"`
	ApproveBy                       int       `gorm:"column:approve_by"`
	ApproveDate                     time.Time `gorm:"column:approve_date"`
	Year                            int       `gorm:"column:year"`
	Geom                            string    `gorm:"column:geom"`
	SectionPartIdRevision           int       `gorm:"column:section_part_id_revision"`
	SubsectionIdRevision            int       `gorm:"column:subsection_id_revision"`
	NeedUpdate                      bool      `gorm:"column:need_update"`
	ApproveComment                  string    `gorm:"column:approve_comment"`
	MainId                          int       `gorm:"column:main_id"`
	RoadRevision                    int       `gorm:"column:road_revision"`
	LaneCount2                      int       `gorm:"column:lane_count2"`
	ShoulderWidth                   float64   `gorm:"column:shoulder_width"`
	ShoulderWidth2                  float64   `gorm:"column:shoulder_width2"`
	ShoulderWidth3                  float64   `gorm:"column:shoulder_width3"`
	ShoulderWidth4                  float64   `gorm:"column:shoulder_width4"`
	RoadCode                        string    `gorm:"column:road_code"`
	SectionCode                     string    `gorm:"column:section_code"`
	Latitude                        float64   `gorm:"column:latitude"`
	Longitude                       float64   `gorm:"column:longitude"`
	DepotName                       string    `gorm:"column:depot_name"`
	SectionKmStart                  string    `gorm:"column:section_km_start"`
	SectionKmEnd                    string    `gorm:"column:section_km_end"`
	FeatureTypeId                   int       `gorm:"column:feature_type_id"`
	FeatureTypeText                 string    `gorm:"column:feature_type_text"`
	Agency2TypeId                   int       `gorm:"column:agency2_type_id"`
	Agency2TypeText                 string    `gorm:"column:agency2_type_text"`
	Agency3TypeId                   int       `gorm:"column:agency3_type_id"`
	Agency3TypeText                 string    `gorm:"column:agency3_type_text"`
	Agency4TypeId                   int       `gorm:"column:agency4_type_id"`
	Agency4TypeText                 string    `gorm:"column:agency4_type_text"`
	ResponsibleTrafficlightTypeId   int       `gorm:"column:responsible_trafficlight_type_id"`
	ResponsibleTrafficlightTypeText string    `gorm:"column:responsible_trafficlight_type_text"`
	ResponsibleFlashlightTypeId     int       `gorm:"column:responsible_flashlight_type_id"`
	ResponsibleFlashlightTypeText   string    `gorm:"column:responsible_flashlight_type_text"`
	ResponsibleTrafficSignTypeId    int       `gorm:"column:responsible_traffic_sign_type_id"`
	ResponsibleTrafficSignTypeText  string    `gorm:"column:responsible_traffic_sign_type_text"`
	ResponsibleLightTypeId          int       `gorm:"column:responsible_light_type_id"`
	ResponsibleLightTypeText        string    `gorm:"column:responsible_light_type_text"`
	ResponsibleLightFlTypeId        int       `gorm:"column:responsible_light_fl_type_id"`
	ResponsibleLightFlTypeText      string    `gorm:"column:responsible_light_fl_type_text"`
	ResponsibleLightHmTypeId        int       `gorm:"column:responsible_light_hm_type_id"`
	ResponsibleLightHmTypeText      string    `gorm:"column:responsible_light_hm_type_text"`
	ResponsibleLightOtherTypeId     int       `gorm:"column:responsible_light_other_type_id"`
	ResponsibleLightOtherTypeText   string    `gorm:"column:responsible_light_other_type_text"`
	SurfaceTypeId                   int       `gorm:"column:surface_type_id"`
	SurfaceTypeText                 string    `gorm:"column:surface_type_text"`
	Surface2TypeId                  int       `gorm:"column:surface2_type_id"`
	Surface2TypeText                string    `gorm:"column:surface2_type_text"`
	Surface3TypeId                  int       `gorm:"column:surface3_type_id"`
	Surface3TypeText                string    `gorm:"column:surface3_type_text"`
	Surface4TypeId                  int       `gorm:"column:surface4_type_id"`
	Surface4TypeText                string    `gorm:"column:surface4_type_text"`
	StatusText                      string    `gorm:"column:status_text"`
	RoadId                          int       `gorm:"column:road_id"`
	MimsKmStart                     float64   `gorm:"column:mims_km_start"`
	MimsKmEnd                       float64   `gorm:"column:mims_km_end"`
}

// TableName use to specific table
func (b *Hsms01Intersection) TableName() string {
	return "hsms_01_intersection"
}
