image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  STG_IMAGE_NAME: "komgrip/mims-api-service"

  PROD_IMAGE_NAME: "komgrip/mims-api-service-prod"
  STG_SERVICE_NAME: "mims-api-service"
  PROD_SERVICE_NAME: "mims-api-service-prod"
  LINE_NOTIFY_TOKEN: ""
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1247825810128244778/K4FM_A9nSjlZWF-uwkbJa-dk0obMtiIbvZ9DsTDvIejTKerVDocs5MDY-MBZTetoP4SB"
  APP_PATH: "/home/mims/docker"


stages:
  - build-staging
  - deploy-staging
  - build-production
  - deploy-production

before_script:
  - apk add --no-cache bash
  - apk add --no-cache openssh-client
  - apk add --no-cache  sshpass
  - apk add --no-cache curl

build-staging:
  stage: build-staging
  image: docker:latest
  services:
    - docker:dind

  script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASSWORD
    - docker build  --cache-from $STG_IMAGE_NAME:latest -t $STG_IMAGE_NAME:$CI_PIPELINE_ID . -f docker/Dockerfile.stage
    - docker tag $STG_IMAGE_NAME:$CI_PIPELINE_ID $STG_IMAGE_NAME:latest
    - docker push $STG_IMAGE_NAME:$CI_PIPELINE_ID
    - docker push $STG_IMAGE_NAME:latest
    - docker rmi $STG_IMAGE_NAME:$CI_PIPELINE_ID
  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "failed" ]; then
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Staging | Build '$STG_SERVICE_NAME' ไม่สำเร็จ กรุณาตรวจสอบ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title, color: 16711680,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: never
    - when: never

deploy-staging:
  stage: deploy-staging
  image: docker:latest

  before_script:
    - apk update && apk add --no-cache  jq curl sshpass 
    - |
      # Construct the title message
      TITLE="Staging | ขณะนี้กำลังมีการ Deploy $STG_SERVICE_NAME "

      # Send the notification to Discord
      curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
        --arg title "$TITLE" \
        --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
        --arg msg "$CI_COMMIT_MESSAGE" \
        '{username: "Gitlab", embeds: [{title: $title,color: 3447003 ,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
      )" $DISCORD_WEBHOOK_URL

  script:

    - sshpass -p "$PASS_SSH_STAGING"  ssh -o "StrictHostKeyChecking=no" $SERVER_STAGING "cd $APP_PATH && ls -la  && docker login --username "$DOCKER_REGISTRY_USER" --password  "$DOCKER_REGISTRY_PASSWORD" && docker-compose pull && docker-compose down && docker-compose up -d && docker system prune -af"


  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Staging | Deploy '$STG_SERVICE_NAME' สำเร็จ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title,color: 65280, fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      else
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Staging | Deploy '$STG_SERVICE_NAME' | ไม่สำเร็จ กรุณาตรวจสอบ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title, color: 16711680,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: never
    - when: never

build-production:
  stage: build-production
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASSWORD
    - docker build  --cache-from $PROD_IMAGE_NAME:latest -t $PROD_IMAGE_NAME:$CI_PIPELINE_ID . -f docker/Dockerfile.prod
    - docker tag $PROD_IMAGE_NAME:$CI_PIPELINE_ID $PROD_IMAGE_NAME:latest
    - docker push $PROD_IMAGE_NAME:$CI_PIPELINE_ID
    - docker push $PROD_IMAGE_NAME:latest
    - docker rmi $PROD_IMAGE_NAME:$CI_PIPELINE_ID

  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "failed" ]; then
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Production | Build '$PROD_SERVICE_NAME' ไม่สำเร็จ กรุณาตรวจสอบ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title, color: 16711680,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: never
    - when: never

deploy-production:
  stage: deploy-production
  image: docker:stable
  
  before_script:
    - apk update && apk add --no-cache  jq curl sshpass 
    - |
      # Construct the title message
      TITLE="Production | ขณะนี้กำลังมีการ Deploy $PROD_SERVICE_NAME "

      # Send the notification to Discord
      curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
        --arg title "$TITLE" \
        --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
        --arg msg "$CI_COMMIT_MESSAGE" \
        '{username: "Gitlab", embeds: [{title: $title,color: 3447003 ,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
      )" $DISCORD_WEBHOOK_URL

  script:
    - sshpass -p "$PASS_SSH_PRODUCTION"  ssh -o "StrictHostKeyChecking=no" $SERVER_PRODUCTION "cd $APP_PATH && ls -la  && docker login --username "$DOCKER_REGISTRY_USER" --password  "$DOCKER_REGISTRY_PASSWORD" && docker-compose pull && docker-compose down && docker-compose up -d && docker system prune -af"

  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Production | Deploy '$PROD_SERVICE_NAME' สำเร็จ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title,color: 65280, fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      else
        curl -X POST -H 'Content-type: application/json' --data "$(jq -n \
          --arg title "Production | Deploy '$PROD_SERVICE_NAME' | ไม่สำเร็จ กรุณาตรวจสอบ" \
          --arg link "[View Pipeline]($CI_PIPELINE_URL)" \
          --arg msg "$CI_COMMIT_MESSAGE" \
          '{username: "Gitlab", embeds: [{title: $title, color: 16711680,fields: [{name: "Message", value: $msg},{name: "Link", value: $link}]}]}' \
        )" $DISCORD_WEBHOOK_URL
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: never
    - when: never

