FROM golang:1.23-alpine

LABEL maintainer="Komgrip <thanandorn@komgrip.com>"
LABEL description="Development environment with hot reload (air)"

RUN apk add --no-cache \
    git \
    make \
    gcc \
    musl-dev

RUN go install github.com/air-verse/air@v1.61.5

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
