ALTER TABLE users DROP CONSTRAINT IF EXISTS check_user_role;
UPDATE users SET role = 'ENGINEER' WHERE role = 'CHIEF_ENGINEER';
ALTER TABLE users ADD CONSTRAINT check_user_role CHECK (role IN ('CEO', 'MANAGER', 'PRODUCT_OWNER', 'ENGINEER', 'SUPPORT'));
