// Code generated by mockery v2.42.0. DO NOT EDIT.

package repomocks

import (
	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/mims-api-service/models"
	gorm "gorm.io/gorm"

	requests "gitlab.com/mims-api-service/requests"

	responses "gitlab.com/mims-api-service/responses"
)

// RoadRepository is an autogenerated mock type for the RoadRepository type
type RoadRepository struct {
	mock.Mock
}

// Commit provides a mock function with given fields: tx
func (_m *RoadRepository) Commit(tx *gorm.DB) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountParent provides a mock function with given fields: tx, roadId
func (_m *RoadRepository) CountParent(tx *gorm.DB, roadId int) (*int64, error) {
	ret := _m.Called(tx, roadId)

	if len(ret) == 0 {
		panic("no return value specified for CountParent")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) (*int64, error)); ok {
		return rf(tx, roadId)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) *int64); ok {
		r0 = rf(tx, roadId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, int) error); ok {
		r1 = rf(tx, roadId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateData provides a mock function with given fields: tx, model
func (_m *RoadRepository) CreateData(tx *gorm.DB, model interface{}) error {
	ret := _m.Called(tx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, interface{}) error); ok {
		r0 = rf(tx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRoadGeom provides a mock function with given fields: tx, roadGeoms
func (_m *RoadRepository) CreateRoadGeom(tx *gorm.DB, roadGeoms []models.RoadGeom) error {
	ret := _m.Called(tx, roadGeoms)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoadGeom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []models.RoadGeom) error); ok {
		r0 = rf(tx, roadGeoms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRoadInfo provides a mock function with given fields: tx, roadInfo
func (_m *RoadRepository) CreateRoadInfo(tx *gorm.DB, roadInfo *models.RoadInfo) error {
	ret := _m.Called(tx, roadInfo)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoadInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.RoadInfo) error); ok {
		r0 = rf(tx, roadInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoad provides a mock function with given fields: tx, roadID, userID
func (_m *RoadRepository) DeleteRoad(tx *gorm.DB, roadID int, userID int) error {
	ret := _m.Called(tx, roadID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoad")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int) error); ok {
		r0 = rf(tx, roadID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoadGeom provides a mock function with given fields: tx, userID, roadID
func (_m *RoadRepository) DeleteRoadGeom(tx *gorm.DB, userID int, roadID int) error {
	ret := _m.Called(tx, userID, roadID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoadGeom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int) error); ok {
		r0 = rf(tx, userID, roadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoadInfo provides a mock function with given fields: tx, roadID, userID
func (_m *RoadRepository) DeleteRoadInfo(tx *gorm.DB, roadID int, userID int) error {
	ret := _m.Called(tx, roadID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoadInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int) error); ok {
		r0 = rf(tx, roadID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccessControl provides a mock function with given fields: _a0
func (_m *RoadRepository) GetAccessControl(_a0 []int) ([]models.AccessControl, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessControl")
	}

	var r0 []models.AccessControl
	var r1 error
	if rf, ok := ret.Get(0).(func([]int) ([]models.AccessControl, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]int) []models.AccessControl); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AccessControl)
		}
	}

	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataById provides a mock function with given fields: _a0, _a1
func (_m *RoadRepository) GetDataById(_a0 interface{}, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDataById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastRoadInfoByID provides a mock function with given fields: roadID
func (_m *RoadRepository) GetLastRoadInfoByID(roadID int) (models.RoadInfoGeomData, error) {
	ret := _m.Called(roadID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRoadInfoByID")
	}

	var r0 models.RoadInfoGeomData
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.RoadInfoGeomData, error)); ok {
		return rf(roadID)
	}
	if rf, ok := ret.Get(0).(func(int) models.RoadInfoGeomData); ok {
		r0 = rf(roadID)
	} else {
		r0 = ret.Get(0).(models.RoadInfoGeomData)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadByID provides a mock function with given fields: roadID
func (_m *RoadRepository) GetRoadByID(roadID int) (*models.RoadById, error) {
	ret := _m.Called(roadID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadByID")
	}

	var r0 *models.RoadById
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.RoadById, error)); ok {
		return rf(roadID)
	}
	if rf, ok := ret.Get(0).(func(int) *models.RoadById); ok {
		r0 = rf(roadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoadById)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadByRoadGrpID provides a mock function with given fields: roadGrpID
func (_m *RoadRepository) GetRoadByRoadGrpID(roadGrpID int) ([]models.RoadInfo, error) {
	ret := _m.Called(roadGrpID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadByRoadGrpID")
	}

	var r0 []models.RoadInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.RoadInfo, error)); ok {
		return rf(roadGrpID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.RoadInfo); ok {
		r0 = rf(roadGrpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadGrpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadDetailMenu provides a mock function with given fields: _a0, _a1, _a2
func (_m *RoadRepository) GetRoadDetailMenu(_a0 []string, _a1 int, _a2 string) ([]responses.RoadMenuData, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadDetailMenu")
	}

	var r0 []responses.RoadMenuData
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, int, string) ([]responses.RoadMenuData, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func([]string, int, string) []responses.RoadMenuData); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.RoadMenuData)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, int, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadDirectionLaneList provides a mock function with given fields: _a0
func (_m *RoadRepository) GetRoadDirectionLaneList(_a0 int) (models.RoadInfoGeomDirection, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadDirectionLaneList")
	}

	var r0 models.RoadInfoGeomDirection
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.RoadInfoGeomDirection, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) models.RoadInfoGeomDirection); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.RoadInfoGeomDirection)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadGroup provides a mock function with given fields:
func (_m *RoadRepository) GetRoadGroup() ([]models.RoadGroup, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoadGroup")
	}

	var r0 []models.RoadGroup
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.RoadGroup, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.RoadGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadGroup)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadGroupList provides a mock function with given fields: _a0
func (_m *RoadRepository) GetRoadGroupList(_a0 requests.RoadPrams) ([]models.RoadList, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadGroupList")
	}

	var r0 []models.RoadList
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.RoadPrams) ([]models.RoadList, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(requests.RoadPrams) []models.RoadList); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadList)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.RoadPrams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadInfoByRoadID provides a mock function with given fields: roadID
func (_m *RoadRepository) GetRoadInfoByRoadID(roadID int) (models.RoadInfo, error) {
	ret := _m.Called(roadID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadInfoByRoadID")
	}

	var r0 models.RoadInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.RoadInfo, error)); ok {
		return rf(roadID)
	}
	if rf, ok := ret.Get(0).(func(int) models.RoadInfo); ok {
		r0 = rf(roadID)
	} else {
		r0 = ret.Get(0).(models.RoadInfo)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadInitData provides a mock function with given fields:
func (_m *RoadRepository) GetRoadInitData() ([]models.RoadListInit, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoadInitData")
	}

	var r0 []models.RoadListInit
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.RoadListInit, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.RoadListInit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadListInit)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadLanes provides a mock function with given fields: roadID
func (_m *RoadRepository) GetRoadLanes(roadID int) ([]models.RoadLanes, error) {
	ret := _m.Called(roadID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadLanes")
	}

	var r0 []models.RoadLanes
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.RoadLanes, error)); ok {
		return rf(roadID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.RoadLanes); ok {
		r0 = rf(roadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadLanes)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadMaxSeq provides a mock function with given fields:
func (_m *RoadRepository) GetRoadMaxSeq() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoadMaxSeq")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadSectionByID provides a mock function with given fields: _a0
func (_m *RoadRepository) GetRoadSectionByID(_a0 int) (*models.RoadSectionById, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadSectionByID")
	}

	var r0 *models.RoadSectionById
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.RoadSectionById, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) *models.RoadSectionById); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoadSectionById)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadStatusSurface provides a mock function with given fields: _a0
func (_m *RoadRepository) GetRoadStatusSurface(_a0 int) (responses.StatusCount, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRoadStatusSurface")
	}

	var r0 responses.StatusCount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (responses.StatusCount, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) responses.StatusCount); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(responses.StatusCount)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoadTypeIcon provides a mock function with given fields:
func (_m *RoadRepository) GetRoadTypeIcon() ([]models.RefRoadTypeIcon, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoadTypeIcon")
	}

	var r0 []models.RefRoadTypeIcon
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.RefRoadTypeIcon, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.RefRoadTypeIcon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RefRoadTypeIcon)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRole provides a mock function with given fields: _a0
func (_m *RoadRepository) GetRole(_a0 uint) ([]models.UserRole, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 []models.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.UserRole, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.UserRole); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: _a0
func (_m *RoadRepository) GetUserById(_a0 uint) (models.Users, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (models.Users, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) models.Users); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Users)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDepartmentById provides a mock function with given fields: _a0
func (_m *RoadRepository) GetUserDepartmentById(_a0 int) (models.UserDepartment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDepartmentById")
	}

	var r0 models.UserDepartment
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.UserDepartment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) models.UserDepartment); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.UserDepartment)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolumeAadtApproved provides a mock function with given fields: roadGrpID
func (_m *RoadRepository) GetVolumeAadtApproved(roadGrpID int) (responses.StatusCount, error) {
	ret := _m.Called(roadGrpID)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeAadtApproved")
	}

	var r0 responses.StatusCount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (responses.StatusCount, error)); ok {
		return rf(roadGrpID)
	}
	if rf, ok := ret.Get(0).(func(int) responses.StatusCount); ok {
		r0 = rf(roadGrpID)
	} else {
		r0 = ret.Get(0).(responses.StatusCount)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadGrpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolumeAccidentApproved provides a mock function with given fields: roadGrpID
func (_m *RoadRepository) GetVolumeAccidentApproved(roadGrpID int) (responses.StatusCount, error) {
	ret := _m.Called(roadGrpID)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeAccidentApproved")
	}

	var r0 responses.StatusCount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (responses.StatusCount, error)); ok {
		return rf(roadGrpID)
	}
	if rf, ok := ret.Get(0).(func(int) responses.StatusCount); ok {
		r0 = rf(roadGrpID)
	} else {
		r0 = ret.Get(0).(responses.StatusCount)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roadGrpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollBack provides a mock function with given fields: tx
func (_m *RoadRepository) RollBack(tx *gorm.DB) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollBack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartTransSection provides a mock function with given fields:
func (_m *RoadRepository) StartTransSection() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartTransSection")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// UpdateDirectionRoad provides a mock function with given fields: tx, roadID, refDirectionId
func (_m *RoadRepository) UpdateDirectionRoad(tx *gorm.DB, roadID int, refDirectionId int) error {
	ret := _m.Called(tx, roadID, refDirectionId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDirectionRoad")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int) error); ok {
		r0 = rf(tx, roadID, refDirectionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoadGeom provides a mock function with given fields: tx, roadGeoms
func (_m *RoadRepository) UpdateRoadGeom(tx *gorm.DB, roadGeoms []models.RoadGeom) error {
	ret := _m.Called(tx, roadGeoms)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoadGeom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []models.RoadGeom) error); ok {
		r0 = rf(tx, roadGeoms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoadInfo provides a mock function with given fields: tx, roadInfo
func (_m *RoadRepository) UpdateRoadInfo(tx *gorm.DB, roadInfo *models.RoadInfo) error {
	ret := _m.Called(tx, roadInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoadInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.RoadInfo) error); ok {
		r0 = rf(tx, roadInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoadRepository creates a new instance of RoadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoadRepository {
	mock := &RoadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

func (_m *RoadRepository) GetParamsConditionByID(ID int, conditionType string) (models.ParamsCondition, error)  {
	return models.ParamsCondition{}, nil
}

func (_m *RoadRepository) GetParamsRoadLine(ID int) (models.ParamsRoadLine, error) {
	return models.ParamsRoadLine{}, nil
}

func (_m *RoadRepository)GetroadConditionSurvey(roadID int, laneNo int) ([]models.RoadConditionSurvey, error) {
	return []models.RoadConditionSurvey{}, nil
}

func (_m *RoadRepository)GetRoadSurfaceLaneAll(roadIds []int) (map[int][]models.RoadSurfaceLane, error){
	return map[int][]models.RoadSurfaceLane{}, nil
}

func (_m *RoadRepository)GetroadConditionSurvey100M(roadID, laneNo int) ([]models.RoadConditionSurvey100M, error){
	return []models.RoadConditionSurvey100M{}, nil
}

func (_m *RoadRepository)GetRoadRetroReflectivity100M(roadID, laneNo int) ([]models.RoadRetroReflectivityRange, error){
	return []models.RoadRetroReflectivityRange{}, nil
}

func (_m *RoadRepository)GetRoadID(params requests.RoadPrams) ([]int, error){
	return []int{}, nil
}