package requests

// import "gitlab.com/mims-api-service/models"

// type AutoGenerated struct {
// 	Code    string `json:"code"`
// 	Title   string `json:"title"`
// 	Message string `json:"message"`
// 	Data    []models.AssetLocation
// }
