package domains

import (
	"time"

	"gitlab.com/mims-api-service/models"
	"gitlab.com/mims-api-service/requests"
	"gitlab.com/mims-api-service/responses"
	"go.mongodb.org/mongo-driver/mongo"
)

type Usecase interface {
	GetReportType1(id int, userID int, typeFile string) (interface{}, error)
	GetReportType2(id int, userID int, typeFile string) (interface{}, error)
	GetReportType3(id int, userID int, typeFile string) (interface{}, error)
	GetReportType4(id int, userID int, plan int, typeFile string) (interface{}, error)
	GetReportType5(id, userID int, plan int, typeFile string) (interface{}, error)
	GetMaintenanceAnalysis(userID int, filter requests.AnalysisFilter, limit, offset int64) ([]responses.AnalysisRes, int64, error)
	GetMaintenanceAnalysisById(ID int, userID int) (interface{}, error)
	CreateMaintenanceAnalysis(userID int, req requests.MaintenanceAnalysis) (interface{}, error)
	UpdateMaintenanceAnalysis(ID int, userID int, req requests.MaintenanceAnalysis) (interface{}, error)
	SelectdPrepareData(id int, prepareDataID []int) error
	UpdateMaintenanceAnalysisCondition(ID int, userID int, req requests.AnalyzingReq) (interface{}, error)
	GetMaintenanceAnalysisConditionById(ID int, prepareDataID []int) (interface{}, error)
	DeleteMaintenanceAnalysis(ID int) error
	CopyMaintenanceAnalysis(ID int) (interface{}, error)
	FavoriteMaintenanceAnalysis(ID int) (responses.AnalysisIsFavorite, error)
	GetPrepareData(analysisID int, req requests.MaintenanceAnalysis) (interface{}, error)
	PrepareDataFn(analysisID int, roads []responses.Road, roadDateBegins []responses.RoadDateBegins, roadGeom []responses.RoadGeoms, roadSurfaces map[string][]models.RoadSurfacePrepareData, maintenances map[int][]responses.MaintenanceData, growthRates map[int]models.SettingAadtGrowthRate, aadtParameters map[int]models.AadtParameterData, groupKm int, surfaceTypeId int) (interface{}, error)
	GetRoadSurface() ([]models.RoadSurface, error)
	GetMaintenanceData(roadId int, laneNo int) (interface{}, error) //([]models.MaintenanceData, error)
	// GetMaintenanceByID(mID int) (models.MaintenanceData, error)
	GetRoadGroupByID(ID int) (models.RoadGroup, error)
	GetRoadByID(roadID int) (models.RoadInfo, error)
	GetRoadDatebegin(roadID int) ([]models.RoadDatebegin, error)
	GetRoadGroupByRoadID(roadID int) (models.Road, error)
	GetRoadGeomLaneByID(roadID int, laneNo int) (models.RoadGeom, error)
	GetRefStructureSurfaceByID(ID int) (models.RefStructureSurface, error)
	GetRoadSurfaceLaneBySurfaceIDByLane(surfaceID int, laneNo int) (models.RoadSurfaceLane, error)
	GetRefSurfaceByID(ID int) (models.RefSurface, error)
	GetRefSurfaceParam(id int) (models.RefSurface, error)
	GetRefMaterialBaseByID(ID int) (models.RefMaterialBase, error)
	GetRefMaterialSubgradeByID(ID int) (models.RefMaterialSubgrade, error)
	GetRefMaterialSubbaseByID(ID int) (models.RefMaterialSubbase, error)
	GetInterventionCriteria() (map[int]models.InterventionCriteria, error)
	GetCriteriaMethod() (map[int]models.RefCriteriaMethod, error)
	GetRoadWorkEffect() (models.SettingRoadWorkEffect, error)
	GetSettingAadtParams(roadGrpID int) (int, map[string]interface{}, error)
	GetRoadSurfaceByRoadID(roadId int, laneNo int) ([]models.RoadSurfacePrepareData, error)
	GetRefCriteriaMethodByID(ID int) (models.RefCriteriaMethod, error)
	GetInterventionCriteriaParamsById(ID int) (models.SettingInterventionCriteriaParams, error)
	GetRrefSurfacrParamsById(ID int) (models.RefSurface, error)
	GetRoadCondition(roadID int, laneNo int) ([]models.RoadConditionSurveyM, time.Time, error)
	GetRoadConditionPrepareData(directionID int, laneNo int, roadConditions []models.RoadConditionSurveyM, road map[string]interface{}) (responses.RoadConditionPrepareDataRes, error)
	GetRoadDamage(roadID int, laneNo int) ([]models.RoadDamageMPrepareData, time.Time, error)
	GetRoadDamagePrepareData(directionID int, laneNo int, roadDamage []models.RoadDamageMPrepareData, road map[string]interface{}) (responses.RoadDamagePrepareDataRes, error)
	GetVolumeAadt(roadGroupID int) (responses.VolumeAadtPrepareDataRes, error)
	GetVolumeRain(roadGroupID int) (responses.VolumeRainPrepareDataRes, error)
	GetCurrentSurface(road map[string]interface{}, surveyDate interface{}) (interface{}, error)
	GetAgeAC(road map[string]interface{}, surveyDate interface{}) (interface{}, error)
	GetAgeCC(road map[string]interface{}, surveyDate interface{}) (interface{}, error)
	GetHsoldHsnew(road map[string]interface{}, surveyDate interface{}) (interface{}, error)
	GetSnp(road map[string]interface{}, surveyDate interface{}) (interface{}, error)
	GetSettingAadtGrowthRate(RoadGrpID int) (models.SettingAadtGrowthRate, error)
	GetSettingAadtParameter(RoadGrpID int) (models.AadtParameterData, error)
	GetLoadEquivalent(ID int) (models.RefAadtParameterVehicleType, error)
	GetType(road map[string]interface{}, surveyDate interface{}) (int, int)
	GetMaintenanceAnalysisPreviousID(ID int) (int, error)
	DashboardStrategicMaintenanceAnalysis(id string, userID int) (interface{}, error)
	DashboardAnnualMaintenanceAnalysis(id string, userID int) (interface{}, error)
	AnalysisModel(ID int)
	ExportData(ID int) (interface{}, error)
	Report1Excel(ID int, userID int) (interface{}, error)
	Report2Excel(ID, userID int) (interface{}, error)
	GetReportType3Excel(id int, userID int) (interface{}, error)
	Report4Excel(id, userID int, plan int) (interface{}, error)
	Report5Excel(id, userID int, plan int, typeFile string) (interface{}, error)
	GetAnalysisModel(ID int, req requests.MaintenanceAnalysisModel) (interface{}, error)
	GetRefCriteriaMethod() (interface{}, error)
	UpdateAnalysisModel(ID int, req []requests.MaintenanceAnalysisModelReq) (interface{}, error)
	DashboardMapFilter(ID int) (interface{}, error)
	DashboardMap(ID int, req requests.MapFilter) (interface{}, error)

	// New
	CheckPrepareDataById(ID int) (interface{}, error)
	GetPrepareDataIdById(ID int) (interface{}, error)
	GetPrepareDataById(ID int) (interface{}, error)
	GetPrepareDataAllByAnalysisSelected(ID int) (interface{}, error)
}

type Repository interface {
	GetMaintenanceAnalysis(filter requests.AnalysisFilter, isAllData, isOwnerData bool, depotCode string, limit, offset int64) ([]models.MaintenanceAnalysisPreload, error)
	GetMaintenanceAnalysisCount(filter requests.AnalysisFilter, isAllData, isOwnerData bool, depotCode string) (int64, error)
	GetMaintenanceAnalysisById(ID int) (models.MaintenanceAnalysis, error)
	CreateMaintenanceAnalysis(maintenanceAnalysis models.MaintenanceAnalysis) (models.MaintenanceAnalysis, error)
	CreateMaintenanceAnalysisRoad(ID int, userID int, roadIDs []int) error
	UpdateMaintenanceAnalysisStep2(id int, req models.MaintenanceAnalysis) error
	SelectdPrepareData(id int, prepareDataID []int) error
	CreateMaintenanceAnalysisStrategic(maintenanceAnalysisStrategic models.MaintenanceAnalysisStrategic) (models.MaintenanceAnalysisStrategic, error)
	CreateMaintenanceAnalysisPlan(ID int, maintenanceAnalysisPlan []models.MaintenanceAnalysisPlan) error
	GetMaintenanceAnalysisConditionById(id int) (models.MaintenanceAnalysisStrategic, error)
	GetMaintenanceAnalysisPlanById(id int) (models.MaintenanceAnalysisPlan, error)
	GetMaintenanceAnalysisPlanByAnalysisID(ID int) ([]models.MaintenanceAnalysisPlan, error)
	UpdateMaintenanceAnalysisPlan(maintenanceAnalysisPlan models.MaintenanceAnalysisPlan) error
	DeleteMaintenanceAnalysisPlandById(ID int) error
	GetMaintenanceAnalysisRoadByID(ID int) ([]models.MaintenanceAnalysisRoads, error)
	ClearPrepareData(ID int) error

	GetPrepareDataByAnalysisID(analysisID int) (interface{}, error)
	GetPrepareDataByAnalysis(analysisID int, prepareDataID []int) ([]models.PrepareData, error)
	DeleteMaintenanceAnalysis(ID int) error
	CopyMaintenanceAnalysis(ID int) (models.MaintenanceAnalysis, error)
	FavoriteMaintenanceAnalysis(ID int) error
	GetRoadSurface() ([]models.RoadSurface, error)
	GetMaintenanceData(roadId int, laneNo int) ([]models.MaintenanceData, error)
	GetMaintenanceByID(mID int) (models.MaintenanceData, error)
	GetRoadGroupByID(ID int) (models.RoadGroup, error)
	GetRoadByID(roadID int) (models.Road, error)
	GetRoadInfoByID(roadID int) (models.RoadInfo, error)
	GetRoadDatebegin(roadID int) ([]models.RoadDatebegin, error)
	GetRoadByRoadID(roadID int) (models.Road, error)
	GetRoadGeomLaneByID(roadID int, laneNo int) (models.RoadGeom, error)
	GetRefStructureSurfaceByID(ID int) (models.RefStructureSurface, error)
	GetRoadSurfaceLaneBySurfaceIDByLane(surfaceID int, laneNo int) (models.RoadSurfaceLane, error)
	GetRefSurfaceByID(ID int) (models.RefSurface, error)
	GetRefSurfaceParam(id int) (models.RefSurfaceParam, error)
	GetRefMaterialBaseByID(ID int) (models.RefMaterialBase, error)
	GetRefMaterialSubgradeByID(ID int) (models.RefMaterialSubgrade, error)
	GetRefMaterialSubbaseByID(ID int) (models.RefMaterialSubbase, error)
	GetInterventionCriteria() ([]models.InterventionCriteria, error)
	GetCriteriaMethod() ([]models.RefCriteriaMethod, error)
	GetRoadWorkEffect() (models.SettingRoadWorkEffect, error)
	GetSettingAadtParams() (models.SettingAadtParams, error)
	GetRoadSurfaceByRoadID(roadID int, laneNo int, grp int) ([]models.RoadSurfacePrepareData, error)
	GetRoadSurfaceByGroupRoadID(roadID int, laneNo int) ([]int, error)
	GetInterventionCriteriaParamsById(ID int) (models.SettingInterventionCriteriaParams, error)
	GetRefCriteriaMethodByID(ID int) (models.RefCriteriaMethod, error)
	GetRrefSurfacrParamsById(ID int) (models.RefSurfaceParam, error)
	GetRoadCondition(roadID int, laneNo int) ([]models.RoadConditionSurveyM, time.Time, error)
	GetRoadDamage(roadID int, laneNo int) ([]models.RoadDamageMPrepareData, time.Time, error)
	GetVolumeAadt(roadGroupID int) (models.VolumeAadt, error)
	GetVolumeRain(roadGroupID int) (models.VolumeRain, error)
	GetRefMaterialBaseConcretePavement() (models.RefMaterialBase, error)
	GetSettingRoadWorkEffect() (models.SettingRoadWorkEffectParams, error)
	GetSettingAadtGrowthRate(RoadGrpID int) (models.SettingAadtGrowthRate, error)
	GetSettingAadtParameter(RoadGrpID int) (models.AadtParameterData, error)
	GetLoadEquivalent(ID int) (models.RefAadtParameterVehicleType, error)
	CreateFullPrepareData(data models.PrepareData) (models.PrepareData, error)
	GetModelResultDataById(ID int) ([]models.ModelResult, error)
	GetLatestPrepareDataByMaintenanceAnalysisId(id int) (models.PrepareData, error)
	GetMaintenanceAnalysisStrategicBudgetTypeById(id int) (models.RefMaintenanceAnalysisCondition, error)
	GetMaintenanceAnalysisStrategiTargetById(id int) (models.RefMaintenanceAnalysisTarget, error)
	GetMaintenanceAnalysisRoadIdById(id int) ([]models.MaintenanceAnalysisRoad, error)
	GetMaintenanceAnalysisRoadDataByID(ID int) (models.MaintenanceAnalysisPreload, error)
	GetMaintenanceAnalysisRoadNameById(id int) ([]models.RoadInfo, error)
	GetRoad() ([]models.RoadInfo, error)
	GetInterventionCriteriaParamsByID() (models.SettingInterventionCriteriaParams, error)
	GetRefCriteriaMethodBySurface(surface string) ([]models.RefCriteriaMethod, error)
	GetMaintenanceAnalysisResult(id int, roadID, plan int, analysisTypeID int) ([]models.ModelResult, error)
	GetMaintenanceAnalysisResultByRoadIDs(id int, roadIDs []int, plan, analysisTypeID int) (map[int][]models.ModelResult, error)
	GetMaintenanceAnalysisResultGroupByYear(id int, plan int, analysisTypeID int) ([]int, error)
	GetUserByID(userId uint) (models.Users, error)
	GetMaintenanceHistoryByRoadID(roadID int, year int) (models.MaintainPreloadGetAll, error)
	GetRoadSurfaceByRoadIDYear(roadId int, laneNo int, year int) ([]models.RoadSurfacePrepareData, error)
	GetRoadSurfaceFirstGrpByRoadID(roadId int, laneNo int) ([]models.RoadSurfacePrepareData, error)
	GetReport4(id int, plan int) ([]models.ModelResult, error)
	GetRoadAll() ([]models.Road, error)
	GetMaintenanceAnalysisPreviousID(ID int) (int, error)
	GetAnalysisModel(ID int, req requests.MaintenanceAnalysisModel) ([]models.ModelResult, error)
	GetRoadInfo() (map[int]models.RoadInfo, error)
	GetRoadGroup() (map[int]models.RoadGroup, error)
	GetRoads() (map[int]models.Road, error)
	GetRefCriteriaMethod() ([]models.RefCriteriaMethod, error)
	GetInterventionCriteriaByID(ID int) ([]models.InterventionCriteria, error)
	UpdateAnalysisModel(ID int, dataID string, interventionCriteriaID int) (*mongo.SingleResult, error)
	GetCriteriaMethodColor() (map[string]string, error)
	GetRoadGeomByRoadIDLaneNo(roadID int, laneNo int) (models.RoadGeom, error)
	GetRefOwner() ([]models.RefOwner, error)
	DashboardMap(ID, analysisTypeID, year int, plan *int) ([]models.ModelResultReportMap, error)

	GetGrade(ids []int) ([]models.RefGrade, error)
	GetRoadConditionGradesByID(ID int) ([]models.ParamsConditionPreload, error)
	GetRefOwnerCondition(ID int) (map[string][]responses.Grade, error)

	GetRoadGroups() ([]models.RoadGroup, error)
	GetRoadSections() ([]models.RoadSection, error)

	// New
	GetPrepareDataIdByMaintenanceAnalysisId(id int) ([]int, error)
	GetPrepareDataById(id int) ([]responses.PrepareDataWithPagination, error)
	UpdatePrepareDataStatusById(id int) error
	GetPrepareDataAllByAnalysisSelected(ID int) ([]models.PrepareData, error)

	GetMaxLane(roadIDs []int) (int, error)

	GetRefDepotByRoad() (map[int]string, error)
	DashboardMapAllYear(ID, analysisTypeID int, plan *int) ([]models.ModelResultReportMap, error)
}
