// Code generated by mockery v2.42.0. DO NOT EDIT.

package helpersmocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/mims-api-service/models"

	multipart "mime/multipart"
)

// HelpersFileDomain is an autogenerated mock type for the HelpersFileDomain type
type HelpersFileDomain struct {
	mock.Mock
}

// EnsureDir provides a mock function with given fields: dirName
func (_m *HelpersFileDomain) EnsureDir(dirName string) error {
	ret := _m.Called(dirName)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dirName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadCenterLaneShepesFile provides a mock function with given fields: centerLanePath
func (_m *HelpersFileDomain) ReadCenterLaneShepesFile(centerLanePath string) ([]models.RoadGeom, error) {
	ret := _m.Called(centerLanePath)

	if len(ret) == 0 {
		panic("no return value specified for ReadCenterLaneShepesFile")
	}

	var r0 []models.RoadGeom
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.RoadGeom, error)); ok {
		return rf(centerLanePath)
	}
	if rf, ok := ret.Get(0).(func(string) []models.RoadGeom); ok {
		r0 = rf(centerLanePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoadGeom)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(centerLanePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadCenterLineShepesFile provides a mock function with given fields: centerLinePath
func (_m *HelpersFileDomain) ReadCenterLineShepesFile(centerLinePath string) (*string, *string, *string, error) {
	ret := _m.Called(centerLinePath)

	if len(ret) == 0 {
		panic("no return value specified for ReadCenterLineShepesFile")
	}

	var r0 *string
	var r1 *string
	var r2 *string
	var r3 error
	if rf, ok := ret.Get(0).(func(string) (*string, *string, *string, error)); ok {
		return rf(centerLinePath)
	}
	if rf, ok := ret.Get(0).(func(string) *string); ok {
		r0 = rf(centerLinePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *string); ok {
		r1 = rf(centerLinePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}

	if rf, ok := ret.Get(2).(func(string) *string); ok {
		r2 = rf(centerLinePath)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*string)
		}
	}

	if rf, ok := ret.Get(3).(func(string) error); ok {
		r3 = rf(centerLinePath)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// SaveFile provides a mock function with given fields: _a0, _a1, _a2
func (_m *HelpersFileDomain) SaveFile(_a0 *gin.Context, _a1 *multipart.FileHeader, _a2 string) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *multipart.FileHeader, string) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *multipart.FileHeader, string) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *multipart.FileHeader, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHelpersFileDomain creates a new instance of HelpersFileDomain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelpersFileDomain(t interface {
	mock.TestingT
	Cleanup(func())
}) *HelpersFileDomain {
	mock := &HelpersFileDomain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
